# Setup
title:               'PyHDL-IF'
tagline:             'A Flexible Python/HDL Interface'
description:         ''
url:                 ''
baseurl:             ''
paginate:            5
#permalink:           pretty

exclude:
    - packages

# About/contact
author:
  name:              Matthew Ballance
  url:               http://mballance.github.io
  email:             matt.ballance@gmail.com
  
github:
  repo: http://github.com/pyhdl-if

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: G-B75HY0XCL2

copyright:             © <!--copyyears--> Matthew Ballance; All rights reserved.
